execute_process(
  COMMAND ${COMMAND0_TO_EXECUTE}
  COMMAND_ERROR_IS_FATAL ANY
  COMMAND_ECHO STDOUT
)
execute_process(
  COMMAND ${COMMAND1_TO_EXECUTE}
  COMMAND_ERROR_IS_FATAL ANY
  COMMAND_ECHO STDOUT
)
